### ISSUE TITLE
Links Fails

### ISSUE THREAD

**Issue by PB314** [springchoi/tumblr_crawler#3]
It appears that the statement

links = soup.find(id='footer').find_all('a')

fails on most pages now.  The error give is

## Crawl... http://subdomain.tumblr.com/page/1
Traceback (most recent call last):
  File "C:\Software\Tumblr Crawler\tumblr.py", line 210, in <module>
    c.do_crawling()
  File "C:\Software\Tumblr Crawler\tumblr.py", line 175, in do_crawling
    links = soup.find(id='footer').find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by springchoi** [comment]
Thanks for reporting,
I fixed code for page link handling

**Comment by PB314** [comment]
Thanks.  Works very well now.  What is the YouTube library for?
